baseURL = "http://retnoika.github.io/"
languageCode = "en-us"
title = "Retno Ika Safitri"
theme = "ris"

[menu]

[[menu.main]]
identifier = "Home"
name = "Home"
title = "Home"
url = "/"
weight = "1"

[[menu.main]]
identifier = "Blog"
name = "Blog"
title = "Blog"
url = "/blog/"
weight = "2"

[[menu.main]]
identifier = "Contact"
name = "Contact"
title = "Contact"
url = "mailto:safitri.retnoika@gmail.com"
weight = "3"

